### ISSUE TITLE
edibles_workshop example 

### ISSUE THREAD

**Issue by AlexRomanec** [jancami/edibles#249]
The following error is given when trying to run the edibles_workshop example

  File ~\edibles\examples\edibles_workshop.py:92
    out = sightline.model.eval(data=sp.flux, params=sightline.result.params, x=sp.wave)

AttributeError: 'Sightline' object has no attribute 'model'

**Comment by alex-ebi** [comment]
Should be fixed now, the correct attribute was complete_model instead of model. I pushed the fix on 'new_python' branch
