### ISSUE TITLE
Na_example 

### ISSUE THREAD

**Issue by Jack-Rawlinson** [jancami/edibles#252]
The graphs produced by this code have a lot of axes overlaps making the graph hard to read. The final line of the code produces this message: 
c:\users\user\edibles\examples\na_example.py:142: MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated since 3.6 and will be removed two minor releases later; explicitly call ax.remove() as needed.
  plt.subplot(122)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by alex-ebi** [comment]
fixed
