### ISSUE TITLE
vrad_from_correlation 

### ISSUE THREAD

**Issue by Jack-Rawlinson** [jancami/edibles#253]
Traceback (most recent call last):

  File ~\.conda\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\user\edibles\examples\vrad_from_correlation.py:85
    sp = EdiblesSpectrum(filename)

  File c:\users\user\edibles\edibles\utils\edibles_spectrum.py:87 in __init__
    self._loadSpectrum()

  File c:\users\user\edibles\edibles\utils\edibles_spectrum.py:94 in _loadSpectrum
    with fits.open(self.filename) as hdulist:

  File ~\.conda\lib\site-packages\astropy\io\fits\hdu\hdulist.py:175 in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,

  File ~\.conda\lib\site-packages\astropy\io\fits\hdu\hdulist.py:410 in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,

  File ~\.conda\lib\site-packages\astropy\io\fits\hdu\hdulist.py:1060 in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)

  File ~\.conda\lib\site-packages\astropy\io\fits\file.py:170 in __init__
    self._open_filename(fileobj, mode, overwrite)

  File ~\.conda\lib\site-packages\astropy\io\fits\file.py:562 in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\DR4_all\\HD183143\\BLUE_346\\HD183143_w346_n1_20180907_B.fits'

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by alex-ebi** [comment]
The script wants to get a merged spectrum. I am not sure if the DR4 directory should contain the orders or the merged spectra.

**Comment by alex-ebi** [comment]
you can fix this by downloading the merged spectra and unpacking the archive to the DR4 directory

download that: [Download the entire archive (all formats; 366M tar file)](https://edibles.astro.uwo.ca/DR4/DR4_all_merged.tar)
