### ISSUE TITLE
MultiNa_NstepCheck and MultiNa_Timer 

### ISSUE THREAD

**Issue by Jack-Rawlinson** [jancami/edibles#254]
Both of these codes run fine, however they both produce this message : 
n_step:  5
Cloud velocities at: [-12]
n_step too small. To avoid under-sampling, n_step reset to 7
I was unsure if this is expected or if this is something that needs to be addressed 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

```python
# Put your Python code snippet here.
```

**Comment by alex-ebi** [comment]
I am not sure either, but i think I will only address errors
