### ISSUE TITLE
Continuum saving technique

### ISSUE THREAD

**Issue by klaykulik** [jancami/edibles#97]
### Description

We want a way to be able to store the continuum anchor points (spline) 

2 parts:

part 1: read in continuum data from fits file
data hosted in separate columns
read file once, get continuum anchors with rest of spectrum data in EdiblesSpectrum
actually build the continuum in Continuum class

part 2: write data to fits file
build function inside Continuum to edit fits file data and header

INITIAL:
- data columns: 

INITIAL_X         INITIAL_Y
x1                    y1
x2                    y2
x3                    y3

- header:

CONTINUUM_METHOD

EDITS
- data columns: 

NAMEDATE1_X         NAMEDATE1_Y
x1                               y1
x2                               y2
x3                               y3

- header:

EDIT_HISTORY = NAMEDATE1, NAMEDATE2
NAMEDATE1_METHOD
NAMEDATE1_USER
NAMEDATE1_DATETIME
NAMEDATE1_COMMENTS

NAMEDATE2_METHOD
NAMEDATE2_USER
NAMEDATE2_DATETIME
NAMEDATE2_COMMENTS

**Comment by kalaschsoyuz** [comment]
Hi, do you mean to store only the anchor points or the resulting spline fit?
I would suggest that if we create a normalised spectrum we store the continuum spectrum (i.e. the spline fit), that was used to divide the original spectrum by. This will be on the same wavelength grid. It can thus be an additional 'FLUX' array in the FITS that we can call 'CONTINUUM' ?

**Comment by klaykulik** [comment]
Hi Nick, our suggestion was to only store spline anchor points, which can be updated/added to. the issue with storing a flux array of continuum points is that updating the values with local observations would introduce flux jumps. if we store anchor points, it is easy to locally generate the same continuum every time, and then create a normalize spectrum.

**Comment by kalaschsoyuz** [comment]
Ok, makes sense. Two options I see with respect to storing this in the FITS product:
1) add FITS keywords to the FITS header which I think can contain an array/list of numbers (?). To store both X and Y values of anchor points add two keywords, e.g. CONT_SPLINE_X and CONT_SPLINE_Y 
2) add new FITS BINTABLE extension "CONTINUUM" which can contain two arrays SPLINE_ANCHOR_X and SPLINE_ANCHOR_Y (and maybe some other information on the type of SPLINE used?)
